ARG FROM_ARG=webdevops/php:latest
FROM ${FROM_ARG}


# 基础
COPY ./docker_entrypoint.d/localtime.sh /opt/docker/bin/entrypoint.d/localtime.sh


COPY ./provision_bootstrap.d/run-eval-env.sh /opt/docker/provision/bootstrap.d/run-eval-env.sh

COPY ./provision-build.d/ /opt/docker/provision/local-build.d
COPY ./script/docker-build-dir.sh /opt/docker/bin/usr-bin/docker-build-dir.sh

ARG BUILD_SCRIPT_ARG=''
RUN bash /opt/docker/bin/usr-bin/docker-build-dir.sh /opt/docker/provision/local-build.d ${BUILD_SCRIPT_ARG}


ONBUILD ARG BUILD_SCRIPT_ARG=''
ONBUILD RUN bash /opt/docker/bin/usr-bin/docker-build-dir.sh /opt/docker/provision/local-build.d ${BUILD_SCRIPT_ARG}