# FROM webdevops/php-nginx:7.2
ARG FROM_ARG="webdevops/php-nginx:7.2"
ARG THINK_CONF="10-location-thinkphp.conf"

FROM ${FROM_IMAGE}

COPY ./nginx-conf.d/${FROM_ARG} /opt/docker/etc/nginx/vhost.common.d/10-location-root.conf
