ARG FROM_ARG=webdevops/php:latest
FROM ${FROM_ARG}


# 基础
COPY ./provision-build.d/ /opt/docker/provision/local-build.d
COPY ./script/docker-build-dir.sh /opt/docker/bin/usr-bin/docker-build-dir.sh


ONBUILD ARG BUILD_SCRIPT_ARG=''
ONBUILD RUN bash /opt/docker/bin/usr-bin/docker-build-dir.sh /opt/docker/provision/local-build.d ${BUILD_SCRIPT_ARG}