ARG FROM_ARG=webdevops/php:latest
FROM ${FROM_ARG}


ARG BUILD_SCRIPT_ARG=''
RUN bash /opt/docker/bin/usr-bin/docker-build-dir.sh /opt/docker/provision/local-build.d ${BUILD_SCRIPT_ARG}


ONBUILD ARG BUILD_SCRIPT_ARG=''
ONBUILD RUN bash /opt/docker/bin/usr-bin/docker-build-dir.sh /opt/docker/provision/local-build.d ${BUILD_SCRIPT_ARG}