ARG BASE_FORM=adockero/php-nginx:7.4-php-alpine

FROM ${BASE_FORM}

COPY ./bin/entrypoint.d/local-supervisord.sh /opt/docker/bin/entrypoint.d/local-supervisord.sh
COPY ./script/local-supervisord/local-supervisor.conf /opt/docker/etc/local-supervisor.conf
COPY ./script/local-supervisord/local-supervisor.d /opt/docker/etc/local-supervisor.d
