ARG FROM_ARG=webdevops/php:7.2
FROM $FROM_ARG

RUN cat ./provision_bootstrap.d/script/git-auto.sh
COPY ./provision_bootstrap.d/cron-git-auto.sh /opt/docker/provision/bootstrap.d/cron-git-auto.sh
COPY ./provision_bootstrap.d/script/git-auto.sh /opt/docker/provision/bootstrap.d/script/git-auto.sh
COPY ./provision_bootstrap.d/script/git-auto-crontab.sh /opt/docker/provision/bootstrap.d/script/git-auto-crontab.sh

COPY ./provision_entrypoint.d/docker-run-bootstrap.sh /opt/docker/provision/entrypoint.d/docker-run-bootstrap.sh
