ARG TAG=latest
#FROM webdevops/php:${TAG}
FROM adockero/php-nginx:${TAG}

COPY ./nginx-conf.d/lua.host.dir.conf /etc/nginx/conf.d/lua.host.dir.conf
COPY ./nginx-conf.d/11-location-thinkphp.conf /opt/docker/etc/nginx/vhost.framework.d/11-location-thinkphp.conf
COPY ./nginx-conf.d/10-php-server_name_host.conf /opt/docker/etc/nginx/vhost.common.d/10-php.conf



COPY ./service.d/ssh.d/11-open-ssh-pwd.sh /opt/docker/bin/service.d/ssh.d/11-open-ssh-pwd.sh