
name: 构建和提交docker-5.6

on:
  push:
    branches:
      - master
    paths: 
      - "**"
      - "./*"
      - "!.github/workflows/*.yml"
      - ".github/workflows/docker-5.6.yml"

jobs:
  setup-build-publish:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像
    steps:
    
    
    
    
    
    
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2







# ----------------base基础start---------------------

    - name: 5.6-base
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 5.6
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.base
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: FROM_ARG=webdevops/php-nginx:5.6
        # Adds labels with git repository information to the built image
        add_git_labels: true




    - name: 5.6-dev
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 5.6-dev
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.base
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: FROM_ARG=webdevops/php-nginx-dev:5.6
        # Adds labels with git repository information to the built image
        add_git_labels: true



# ----------------base基础end---------------------









# ----------------lua基础start---------------------




    - name: 5.6-dev-lua
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 5.6-dev-lua
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=php-nginx:5.6-dev
        # Adds labels with git repository information to the built image
        add_git_labels: true



# ----------------lua基础end---------------------





    # - name: 7.4-lua-host-dir
    #   uses: docker/build-push-action@v1.1.0
    #   with:
    #     # Username used to log in to a Docker registry. If not set then no login will occur
    #     username: adockero
    #     # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
    #     password: ${{ secrets.PASSWORD }}
    #     # Docker repository to tag the image with
    #     repository: adockero/php-nginx
    #     # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
    #     tags: 7.4-lua-host-dir
    #     # Path to the Dockerfile (Default is '{path}/Dockerfile')
    #     # path: ./dockerfile
    #     dockerfile: Dockerfile.lua-host-dir
    #     # Always attempt to pull a newer version of the image
    #     always_pull: true
    #     # Comma-delimited list of build-time variables
    #     build_args: TAG=7.4-lua
    #     # Adds labels with git repository information to the built image
    #     add_git_labels: true



    - name: 5.6-dev-lua-host-dir
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 5.6-dev-lua-host-dir
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua-host-dir
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=5.6-dev-lua
        # Adds labels with git repository information to the built image
        add_git_labels: true






# ----------------其他start---------------------

    - name: 5.6-mysql
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 5.6-mysql
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.mysql
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        # build_args: FROM_ARG=adockero/php-nginx:5.6-mysql
        # Adds labels with git repository information to the built image
        add_git_labels: true

    - name: 5.6-mysql-git-auto
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 5.6-mysql-git-auto
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.git-auto
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: FROM_ARG=adockero/php-nginx:5.6-mysql
        # Adds labels with git repository information to the built image
        add_git_labels: true



# ----------------其他end---------------------

