
name: 构建和提交docker-other

on:
  push:
    branches:
      - master


jobs:
  setup-build-publish:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像
    steps:
    
    
    
    
    
    
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2



    - name: php:7-cli-alpine
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-more
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7-cli-SMProxy
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: ./other/SMProxy-base.Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: FROM_ARG=php:7-cli-alpine,SWOOLE_VERSION=swoole-4.8.11
        # Adds labels with git repository information to the built image
        add_git_labels: true


