
name: 构建和提交docker-7.2

on:
  push:
    branches:
      - master
    paths: 
      - "**"
      - "./*"
      - "!.github/workflows/*.yml"
      - ".github/workflows/docker-7.2.yml"


jobs:
  setup-build-publish:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像
    steps:
    
    
    
    
    
    
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2



    - name: 7.2-lua-alpine
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-lua-alpine
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=php-nginx:7.2-alpine
        # Adds labels with git repository information to the built image
        add_git_labels: true




    - name: 7.2-lua
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-lua
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=php-nginx:7.2
        # Adds labels with git repository information to the built image
        add_git_labels: true




    - name: 7.2-dev-lua-alpine
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-dev-lua-alpine
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=php-nginx-dev:7.2-alpine
        # Adds labels with git repository information to the built image
        add_git_labels: true








    - name: 7.2-dev-lua
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-dev-lua
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=php-nginx-dev:7.2
        # Adds labels with git repository information to the built image
        add_git_labels: true



# ----------------lua基础---------------------





    - name: 7.2-lua-host-dir
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-lua-host-dir
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua-host-dir
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=7.2-lua
        # Adds labels with git repository information to the built image
        add_git_labels: true



    - name: 7.2-dev-lua-host-dir
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-dev-lua-host-dir
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.lua-host-dir
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        build_args: TAG=7.2-dev-lua
        # Adds labels with git repository information to the built image
        add_git_labels: true



    - name: 7.2-thinkphp6
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-thinkphp6
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.thinkphp
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        # build_args: FROM_ARG=adockero/php-nginx:5.6-mysql
        # Adds labels with git repository information to the built image
        add_git_labels: true





    - name: 7.2-git-auto
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/php-nginx
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 7.2-git-auto
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # path: ./dockerfile
        dockerfile: Dockerfile.git-auto
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of build-time variables
        # build_args: arg1=value1,arg2=value2
        # Adds labels with git repository information to the built image
        add_git_labels: true



